config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  devise_for :users

  root "pages#home"

  resources :players do
    get "league_filter", on: :member
    resources :player_auths, only: [ :create, :destroy ]
  end
  resources :teams
  resources :matches, except: [ :index ]
  # get "filter", on: :collection

  resources :leagues do
    resources :league_auths, only: [ :create, :destroy ]
    get :auths_user_section, to: "league_auths#user_section"
    resources :memberships, only: [ :create, :destroy ]
    get :memberships_player_section, to: "memberships#player_section"
  end

  scope module: :admin do
    resources :users, only: [ :index, :destroy ] do
      post :impersonate, on: :member, to: "impersonations#create"
    end
    delete "/impersonations/stop", to: "impersonations#destroy", as: :stop_impersonating
  end

  if Rails.env.development?
    get "/debug_session", to: "leagues#show_session"
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/league.rb
class League < ApplicationRecord
  attr_accessor :creator # allows a check on name uniqueness (per admin) at time of creation. Note the creator will be set as the admin, though can potentially subsequently be changed. And creator is not permanently stored.
  has_many :matches, dependent: :destroy
  has_many :league_auths, dependent: :destroy
  has_many :users, through: :league_auths
  has_many :memberships, dependent: :destroy
  has_many :players, through: :memberships
  before_validation :titleize_full_name
  validates :name, presence: true, length: { maximum: 20 }
  validates :season, presence: true, length: { maximum: 20 }
  validates :participants_per_match, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
  validates :participant_type, inclusion: { in: %w[ player team ] }
  # validates :name, uniqueness: { scope: :season, message: "this name/season combination already taken" }
  validate :full_name_unique_for_admin
  scope :order_by_created_at, -> { order(created_at: :desc) }

  def full_name
    "#{name} #{season}"
  end

  # assumes league has just 1 admin for now
  def admin
    users.joins(:league_auths)
         .find_by(league_auths: { role: :admin })
  end

  private

  def titleize_full_name
    self.name = name.strip.titleize
    self.season = season.strip.titleize
  end

  def full_name_unique_for_admin
    return unless creator

    duplicates = creator.leagues.where([ "name = ? and season = ?", name, season ])
    duplicates = duplicates.where.not(id: id) if persisted?
    error_message = "You already have a league named #{name} for Season #{season}"
    if duplicates.exists?
      # want 1 error message but both fields hilighted  - used in conjunction with skipping an error message in the form's league.errors.any? loop
      errors.add(:name, error_message)
      errors.add(:season, "")
    end
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  include SortHelper
  helper_method :sort_column, :sort_direction
  before_action :authenticate_user!
  before_action :set_league, only: [ :show, :edit, :update, :destroy ]
  before_action :authorize_league_access, only: [ :show, :edit, :update, :destroy ]

  def index
    @leagues = current_user.leagues.order_by_created_at.includes(:matches)
    @league_leaders = Player.with_league_stats.group_by(&:league_id).transform_values do |players|
      players.max_by(&:total_score)
    end
    handle_response
  end

  def show
    # filter
    @sort_column, @sort_direction = set_sort_params # e.g. [ "total_score", 'desc' ]
    @participants = Player.with_league_stats(league_id: @league.id).order(order_sql_array.join(", "))
    @match_id = params[:match_id]
    @league_table_close_button = params[:league_table_close_button] == "true" ? true : false
    # @frame_id = @match_id ? "show_league_for_match_#{@match_id}" : "league_#{@league.id}"
    @matches = @league.matches.order_by_date.includes(:league)
    handle_response
  end

  def new
    @league = League.new
  end

  def edit
  end

  def create
    @league = League.new(league_params)
    @league.creator = current_user
    if @league.save
      current_user.league_auths.create!(league: @league, role: :admin)
      flash[:success] = "League was successfully created."
      redirect_to leagues_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @league.update(league_params)
      flash[:success] = "League was successfully updated."
      redirect_to leagues_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @league.destroy!
    flash[:success] = "League was successfully destroyed."
    redirect_to leagues_path
  end

  # quick way to see the sessions hash
  # should be in a Debug controller but didnt want to create a new controller just for it
  def show_session
    render json: session.to_hash, pretty: true
  end

  private

    # def filter
    #   clear_session(:league_id)
    #   session[:league_id] = params[:id] || session[:league_id]
    # end

    def set_league
      @league = League.find(params.expect(:id))
    end

    def handle_response
      respond_to do |format|
        format.turbo_stream
        format.html
      end
    end

    def league_params
      params.expect(league: [ :name, :season, :participants_per_match, :participant_type ])
    end

    def sort_column
      # Sanitizing the search options, so only items specified in the list can get through
      %w[total_score wins].include?(params[:sort]) ? params[:sort] : "total_score"
    end

    def sort_direction
      # additional code provides robust sanitisation of what goes into the order clause
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def set_sort_params
      [ sort_column, sort_direction ]
    end

    def order_sql_array
      tie_breakers = SORT_TIE_BREAKERS[@sort_column] || SORT_TIE_BREAKERS[:default]
      # e.g. [ total_score ASC, wins ASC, first_name ASC ]
      [ "#{sort_column} #{sort_direction}" ] +
      tie_breakers.map { |col| "#{col} #{sort_direction}" } +
      [ "first_name ASC" ]
    end

    def authorize_league_access
      unless @league.users.include?(current_user)
        flash[:warning] = I18n.t(:forbidden)
        redirect_to new_user_session_path
      end
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_with(model: league, class: 'admin_form pt-4 my-1') do |form| %>
  <% if league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
        <% league.errors.each do |error| %>
          <!-- skip empty season error, which implies name/season uniqueness validation failure and name uniqueness already shown -->        
          <% next if error.attribute == :season && error.type.blank? %> 
          <li><%= error.full_message %></li>
        <% end %>        
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.text_field :season %>
  </div>

  <div class="field">
    <%= form.label :participants_per_match %>
    <%= form.number_field :participants_per_match, min: 1, max: 10 %>
  </div>

  <div class="field">
    <%= form.label :participant_type %>
    <%= form.select :participant_type, %w[player team] %>
  </div>

  <div class="actions mt-3">
    <%= form.submit %>
  </div>

  <% if league.new_record? %>
    <div class='cancel' data-controller="form-cancel"><%= link_to 'X', '#', data: { action: 'form-cancel#cancel' } %> </div>  
  <% else %>
    <div class='cancel'><%= link_to 'X', leagues_path %> </div>  
  <% end %>    
<% end %>

app/views/leagues/_league.html.erb
<%= turbo_frame_tag league do %>
  <div class="row">
    <div class="column col-2x"><%= link_to league.name, league_path(league, league_table_close_button: true), class: 'buttonlike' %></div>
    <div class="column col-2x"><%= league.season %></div>
    <div class="column col-2x"><%= league.participants_per_match %></div>
    <div class="column col-2x"><%= league.matches.size || 0 %></div>
    <div class="column col-2x"><%= @league_leaders[league.id]&.full_name %></div>
    <div class="column col-2x"><%= @league_leaders[league.id]&.total_score %></div>
    <div class="column"><%= link_to league_path(league), data: {turbo: false} do %>
                                      <i class="bi bi-clipboard"></i>
                                    <% end %>
    </div>                                    
    <div class="column nomobile"><%= link_to edit_league_path(league),
                                             data: {turbo_frame: dom_id(league)} do %>
                                               <i class="bi bi-pencil-fill"></i>
                                             <% end %>
    </div>
  </div>
<% end %>

app/views/leagues/_league_table.html.erb
<!--turbo-frame id="table_league_27"-->
<%#= turbo_frame_tag 'league-table' do %>
<%= turbo_frame_tag @league do %>
  <div id="league-table" class="canvas gray100-canvas embossed mt-1 mb-2">

    <div class="admin-table my-1">
      <div class="row">
        <div class="column col-1x">Name</div>
        <div class="column col-1x">Matches</div>
        <div class="column col-1x"><%= sortable(column: "wins", match_id: @match_id, sort_column: @sort_column, sort_direction: @sort_direction) %></div>
        <div class="column col-1x"><%= sortable(column: "total_score", match_id: @match_id, sort_column: @sort_column, sort_direction: @sort_direction) %></div>
        <div class="column col-1x">Average Score</div>
        <div class="column col-1x">Position</div>
      </div>
      <% @participants.each_with_index do |participant, index| %>
        <div class="row">
          <div class="column col-1x"><%= link_to participant.full_name, participant, class: 'buttonlike', data: {turbo: false} %></div>
          <div class="column col-1x"><%= participant.matches_played %></div>
          <div class="column col-1x"><%= participant.wins.round(2) %></div>
          <div class="column col-1x"><%= number_with_delimiter(participant.total_score.round(2)) %></div>
          <div class="column col-1x"><%= number_with_delimiter(participant.average_score.round(2)) %></div>
          <div class="column col-1x"><%= index + 1 %></div>
        </div>
      <% end %>
      <% if league_table_close_button %>
        <div class="cancel">
          <%= link_to image_tag('delete.png', class: "table_icon"), leagues_path %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/leagues/_leagues_table.html.erb
<div id="leagues-table" class="match-league-data px-0 mb-5">
  <div class="px-0 mb-5">
    <div class="admin-table mt-2">
      <div class="row fw-bolder">
        <div class="column col-2x">Name</div>
        <div class="column col-2x">Season</div>
        <div class="column col-2x">Participants</div>
        <div class="column col-2x">Matches Played</div>
        <div class="column col-2x">Winner/Leader</div>
        <div class="column col-2x">Winning/Leading Score</div>
        <div class="column nomobile"></div>
        <div class="column nomobile"></div>
      </div>
    </div>
    <div class="admin-table">
      <%= render @leagues %>
    </div>
  </div>
</div>

app/views/leagues/_manage_access_form.html.erb
<% if @league.league_auths.find_by(user: current_user)&.admin? %>
  <div class="canvas gray100-canvas embossed mt-1 mb-2">
    <div class="fst-italic fw-bolder ps-2">Manage Membership</div>
    <div class="admin-table mt-2 mb-4">
      <h2 class="fst-italic ps-1 fs-9">Add Users</h2>
      <%= form_with url: league_league_auths_path(@league), class: 'ps-1' do %>
        <%= text_field_tag :email, nil, placeholder: "User Email" %>
        <div class="actions mt-1 d-inline">
          <%= submit_tag "Add" %>
        </div>
      <% end %>
    </div>

    <div class="admin-table mt-2 mb-4">
      <h2 class="fst-italic ps-2 fs-9">Remove Users</h2>
      <ul class="list-group">
        <% @league.league_auths.each do |membership| %>
          <li class="list-group-item">
            <%= membership.user.email %>
            <% unless membership.admin? %>
              <%= link_to image_tag('delete.png', class: "table_icon"), league_league_auth_path(@league, membership),
                            method: :delete, data: { turbo_method: :delete, confirm: "Remove user?" } %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/leagues/_manage_access_forms.html.erb
<% if @league.league_auths.find_by(user: current_user)&.admin? %>
  <%#= render 'manage_authorisations' %>
  <%= render 'league_auths/user_section_body' %>
  <%= render 'memberships/player_section_body' %>
  <%#= render 'manage_memberships' %>
<% end %>

app/views/leagues/_manage_memberships.html.erb
<div class="canvas gray100-canvas embossed mt-1 mb-2">
  <div class="fst-italic fw-bolder ps-2">Manage Memberships</div>
  <div class="admin-table mt-2 mb-4">
    <h2 class="fst-italic ps-1 fs-9">Add Players</h2>
    <%= form_with url: league_memberships_path(@league), class: 'ps-1' do |form| %>
      <%= form.select :player_id, options_for_select(@addable_players.map {|p| [p.full_name, p.id]}), {}, { class: "sort" } %>
      <div class="d-inline image_actions">
        <%= form.submit 'add' %>
      </div>
    <% end %>
  </div>

  <div class="admin-table mt-2 mb-4">
    <h2 class="fst-italic ps-2 fs-9">Remove Players</h2>
    <ul class="list-group">
      <% @memberships.each do |membership| %>
        <li class="list-group-item">
          <%= membership.player.first_name %>
            <%= link_to image_tag('delete.png', class: "table_icon"), league_membership_path(@league, membership),
                          method: :delete, data: { turbo_method: :delete, confirm: "Remove player?" } %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/leagues/_new_match_heading.html.erb
  <h1 class='h5 mb-2'> <%= "#{@league.full_name} League" %>
    <%= link_to image_tag('add.png', class: "button_icon"),
                new_match_path(league_id: params[:id] ),
                data: { turbo_frame: dom_id(Match.new)} %>
  </h1>

app/views/leagues/edit.html.erb
<% content_for :title, "Editing league" %>
<%= turbo_frame_tag @league do %>
  <%= render "form", league: @league %>
<% end %>

app/views/leagues/index.html.erb
<div class="container px-1">
  <% content_for :title, "Leagues" %>
  <h1 class='h5 mb-2'>Leagues 
    <%= link_to image_tag('add.png', class: "button_icon"), new_league_path, data: { turbo_frame: dom_id(League.new)}, alt: 'New League' %>
  </h1>
  <%= turbo_frame_tag League.new %>
  <%= turbo_frame_tag 'leagues' do %>
    <%= render 'leagues_table' %>
  <% end %>
</div>

app/views/leagues/index.turbo_stream.erb
<%= turbo_stream.update "leagues" do %>
  <%= render partial: "leagues_table" %>
<% end %>
<%= turbo_stream.update "new_league" do %>
  <%= render inline:'' %>
<% end %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>

app/views/leagues/new.html.erb
<% content_for :title, "New league" %>
<%= turbo_frame_tag @league do %>
  <div class="col-md-6 mb-4">
    <%= render "form", league: @league %>
  </div>
<% end %>

app/views/leagues/show.html.erb
<div class="container px-1">
  <%= render 'new_match_heading' %>
  <%= turbo_frame_tag Match.new %>
  <%= render partial: 'league_table', locals: { league_table_close_button: @league_table_close_button } %>
  <%= render 'matches/matches_table' %>
  <%= render 'manage_access_forms' %>
</div>

app/views/leagues/show.turbo_stream.erb
<%= turbo_stream.replace @league do %>
  <%= render partial: "league_table", locals: { league_table_close_button: @league_table_close_button } %>
<% end %>
<%#= turbo_stream.update "new_match" do %>
  <%#= render inline:'' %>
<%# end %>
<%= turbo_stream.replace 'matches-table' do %>
  <%= render "matches/matches_table" %>
<% end %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>