config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  devise_for :users

  root "pages#home"

  resources :players do
    get "league_filter", on: :member
    resources :player_auths, only: [ :create, :destroy ]
  end
  resources :teams
  resources :matches, except: [ :index ]
  # get "filter", on: :collection

  resources :leagues do
    resources :league_auths, only: [ :create, :destroy ]
    get :auths_user_section, to: "league_auths#user_section"
    resources :memberships, only: [ :create, :destroy ]
    get :memberships_player_section, to: "memberships#player_section"
  end

  scope module: :admin do
    resources :users, only: [ :index, :destroy ] do
      post :impersonate, on: :member, to: "impersonations#create"
    end
    delete "/impersonations/stop", to: "impersonations#destroy", as: :stop_impersonating
  end

  if Rails.env.development?
    get "/debug_session", to: "leagues#show_session"
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/navbars/_collapsible.html.erb
<button class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

app/views/navbars/_left.html.erb
<% navbarPresenter = NavbarPresenter.new(user_signed_in?, request.path) %>
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
  <%= navbarPresenter.nav_item_text('Players', players_path, true) %>  
  <%= navbarPresenter.nav_item_text('Leagues', leagues_path, true) %>
  <%= navbarPresenter.nav_item_text('Users', users_path, current_user&.admin? ) %>
</ul>

app/views/navbars/_logo.html.erb
<%= link_to 'league system pro', root_path, class: "navbar-brand me-5" %>

app/views/navbars/_main.html.erb
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <%= render 'navbars/left' %>
  <%= render 'navbars/right' %>  
</div>

app/views/navbars/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-sticky bg-body-tertiary">
  <div class="container">
    <%= render 'navbars/logo' %>
    <%= render 'navbars/collapsible' %>
    <%= render 'navbars/main' %>
  </div>    
</nav>

app/views/navbars/_right.html.erb
<% if user_signed_in? %>
  <ul class="navbar-nav" >
    <li class="nav-item">
      <%= link_to destroy_user_session_path , class: "nav-link", data: {turbo_method: :delete} do %>            
        <i class="bi bi-door-open-fill"></i>
      <% end %>
    </li>
  </ul>
<% end %>