config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  devise_for :users

  root "pages#home"

  resources :players do
    get "league_filter", on: :member
    resources :player_auths, only: [ :create, :destroy ]
  end
  resources :teams
  resources :matches, except: [ :index ]
  # get "filter", on: :collection

  resources :leagues do
    resources :league_auths, only: [ :create, :destroy ]
    get :auths_user_section, to: "league_auths#user_section"
    resources :memberships, only: [ :create, :destroy ]
    get :memberships_player_section, to: "memberships#player_section"
  end

  scope module: :admin do
    resources :users, only: [ :index, :destroy ] do
      post :impersonate, on: :member, to: "impersonations#create"
    end
    delete "/impersonations/stop", to: "impersonations#destroy", as: :stop_impersonating
  end

  if Rails.env.development?
    get "/debug_session", to: "leagues#show_session"
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/player.rb
class Player < ApplicationRecord
  attr_accessor :creator # allows a check on name uniqueness (per admin) at time of creation.
  belongs_to :team, optional: true
  has_many :participations, as: :participant, dependent: :destroy
  has_many :matches, through: :participations
  has_many :leagues, through: :matches
  has_many :player_auths, dependent: :destroy
  has_many :users, through: :player_auths
  has_many :memberships, dependent: :destroy
  before_validation :titleize_full_name
  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  validate :full_name_unique_for_admin
  scope :order_by_name, -> { order(:first_name, :last_name) }

  def self.with_league_stats(league_id: nil)
    # https://ruby-doc.org/core-2.5.0/doc/syntax/literals_rdoc.html To call a method on a heredoc place it after the opening identifier:
    with(
        # Step 1: Get max score per match
        max_scores: Participation
          .where(participant_type: "Player")
          .select("match_id, MAX(score) AS max_score")
          .group(:match_id),

        # Step 2: Count how many players got that max score
        winners: Participation
          .joins("INNER JOIN max_scores ms ON ms.match_id = participations.match_id AND participations.score = ms.max_score")
          .where(participant_type: "Player")
          .select("ms.match_id, ms.max_score, COUNT(*) AS num_winners")
          .group("ms.match_id, ms.max_score")
      )
      .select(<<~SQL)
        players.*,
        matches.league_id,
        COUNT(p.id) AS matches_played,
        SUM(p.score) AS total_score,
        AVG(p.score) AS average_score,
        SUM(
          CASE
            WHEN p.score = w.max_score
            THEN 1.0 / w.num_winners
            ELSE 0
          END
        ) AS wins
      SQL
      .joins("INNER JOIN participations p ON p.participant_id = players.id AND p.participant_type = 'Player'")
      .joins("INNER JOIN matches ON matches.id = p.match_id")
      .joins("INNER JOIN winners w ON w.match_id = p.match_id")
      .group("players.id, matches.league_id")
      .then { |chain| league_id.present? ? chain.where(matches: { league_id: league_id }) : chain }
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin
    users.joins(:player_auths)
         .find_by(player_auths: { role: :admin })
  end

  private

  def titleize_full_name
  self.first_name = first_name.strip.titleize
  self.last_name = last_name.strip.titleize
  end

  def full_name_unique_for_admin
    return unless creator

    duplicates = creator.players.where([ "first_name = ? and last_name = ?", first_name, last_name ]).then { |chain| persisted? ? chain.where.not(id: id) : chain }
    error_message = "You already have a player named #{full_name}"
    if duplicates.exists?
      # want 1 error message but both fields hilighted  - used in conjunction with skipping an error message in the form's player.errors.any? loop
      errors.add(:first_name, error_message)
      errors.add(:last_name, "")
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_player, only: %i[ show edit update destroy league_filter ]
  before_action :authorize_player_access, only: [ :show, :edit, :update, :destroy ]

  def index
    @players = current_user.players.order_by_name
    handle_index_response
  end

  def show
    @league_options = [ [ "All", nil ] ] +
                        @player.leagues.order_by_created_at.distinct.map { |league| [ league.full_name, league.id ] }
    @participations = @player.participations.
                              merge(Match.order_by_date).
                              includes(match: [ :league ]).
                              then { |chain| session.dig(:player_league_ids, @player.id.to_s).present? ? chain.where(matches: { league_id: session.dig(:player_league_ids, @player.id.to_s) }) : chain }
  end

  def league_filter
    session[:player_league_ids]&.delete(@player.id.to_s)
    if (league_id = params[:player_league_id].presence) # when 'All' is selected', nil is passed and the conditional is false so the session[:player_league_ids] for the player does not get set (remains nil).
      session[:player_league_ids] ||= {}
      session[:player_league_ids][@player.id.to_s] = league_id.to_i
    end
    redirect_to @player
  end

  def new
    @player = Player.new
  end

  def edit
  end

  def create
    @player = Player.new(player_params)
    @player.creator = current_user

    if @player.save
      current_user.player_auths.create(player: @player, role: :admin)
      flash[:success] = "Player was successfully created."
      redirect_to players_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @player.update(player_params)
      flash[:success] = "Player was successfully updated."
      redirect_to players_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @player.destroy!
    flash[:success] = "Player was successfully destroyed."
    redirect_to players_path
  end

  private
    def set_player
      @player = Player.find(params.expect(:id))
    end

    def set_league
      @league = League.find_by(id: params[:league_id]) || "All"
    end

    def handle_index_response
      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end

    def player_params
      params.expect(player: [ :first_name, :last_name ])
    end

    def authorize_player_access
      unless @player.users.include?(current_user)
        flash[:warning] = I18n.t(:forbidden)
        redirect_to new_user_session_path
      end
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with(model: player, class: 'admin_form pt-4 my-1') do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>
      <ul>
        <% player.errors.each do |error| %>
          <% next if error.attribute == :last_name && error.type.blank? %> 
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions mt-2">
    <%= form.submit %>
  </div>

  <% if player.new_record? %>
    <div class='cancel' data-controller="form-cancel"><%= link_to 'X', '#', data: { action: 'form-cancel#cancel' } %> </div>  
  <% else %>
    <div class='cancel'><%= link_to 'X', players_path %> </div>  
  <% end %>    
<% end %>

app/views/players/_league_selection.html.erb
<%= form_with(url: league_filter_player_path(@player), method: "get", class: "form-class", data: {turbo_frame: "matches_table"}) do |form| %>  
   <%= form.select :player_league_id,
                   options_for_select(@league_options, session.dig(:player_league_ids, @player.id.to_s)),
                   {},
                   { class: 'sort', onchange: 'this.form.requestSubmit()' } %> 
<% end %>

app/views/players/_manage_access_form.html.erb
<% if @player.player_auths.find_by(user: current_user)&.admin? %>
  <div class="canvas gray100-canvas embossed mt-1 mb-2">
    <div class="fst-italic fw-bolder ps-2">Manage Authorisation</div>
    <div class="admin-table mt-2 mb-4">
      <h2 class="fst-italic ps-1 fs-9">Add Users</h2>
      <%= form_with url: player_player_auths_path(@player), class: 'ps-1' do %>
        <%= text_field_tag :email, nil, placeholder: "User Email" %>
        <div class="actions mt-1 d-inline">
          <%= submit_tag "Add" %>
        </div>
      <% end %>
    </div>

    <div class="admin-table mt-2 mb-4">
      <h2 class="fst-italic ps-2 fs-9">Remove Users</h2>
      <ul class="list-group">
        <% @player.player_auths.each do |auth| %>
          <li class="list-group-item">
            <%= auth.user.email %>
            <% unless auth.admin? %>
              <%= link_to image_tag('delete.png', class: "table_icon"), player_player_auth_path(@player, auth),
                            method: :delete, data: { turbo_method: :delete, confirm: "Remove user?" } %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/players/_matches_table.html.erb
<div id="matches_table" class="match-player-data container px-0 mb-5">
  <div class="container px-0 mb-5">
    <div class="admin-table mt-2">
      <div class="row fw-bolder">
        <div class="column col-2x">Date</div>
        <div class="column col-2x">Score</div>
        <div class="column col-2x">League</div>
      </div>
    </div>
    <div class="admin-table">
      <% @participations.each do |participation| %>
        <div class="row">
          <div class="column col-2x">
            <%= participation.match.date.strftime('%d/%m/%y') %>
          </div>
          <div class="column col-2x"><%= participation.score %></div>
          <div class="column col-2x"><%= link_to participation.match.league.full_name,
                                                league_path(participation.match.league), class: 'buttonlike' %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/players/_player.html.erb
<%= turbo_frame_tag player do %>
  <div class="row">
    <div class="column col-2x"><%= link_to player.full_name, player_path(player), class: 'buttonlike', data: {turbo: false} %></div>                                        
    <div class="column nomobile"><%= link_to edit_player_path(player),
                                             data: {turbo_frame: dom_id(player)} do %>
                                               <i class="bi bi-pencil-fill"></i>
                                             <% end %>
    </div>
  </div>
<% end %>

app/views/players/_players_table.html.erb
<div id="players-table" class="match-player-data container px-0 mb-5">
  <div class="container px-0 mb-5">
    <div class="admin-table mt-2">
      <div class="row fw-bolder">
        <div class="column col-2x">Name</div>
        <div class="column nomobile"></div>
      </div>
    </div>
    <div class="admin-table">
      <%= render @players %>
    </div>
  </div>
</div>

app/views/players/edit.html.erb
<% content_for :title, "Editing player" %>
<%= turbo_frame_tag @player do %>
  <%= render "form", player: @player %>
<% end %>

app/views/players/index.html.erb
<div class="container px-1">
  <% content_for :title, "Players" %>
  <h1 class='h5 mb-2'>Players
    <%= link_to image_tag('add.png', class: "button_icon"), new_player_path, data: { turbo_frame: dom_id(Player.new)} %>
  </h1>
  <%= turbo_frame_tag Player.new %>
  <%= turbo_frame_tag 'players' do %>
    <%= render 'players_table' %>
  <% end %>
</div>

app/views/players/index.turbo_stream.erb
<%= turbo_stream.update "players" do %>
  <%= render partial: "players_table" %>
<% end %>
<%= turbo_stream.update "new_player" do %>
  <%= render inline:'' %>
<% end %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>

app/views/players/new.html.erb
<% content_for :title, "New player" %>
<%= turbo_frame_tag @player do %>
  <div class="col-md-6 mb-4">
    <%= render "form", player: @player %>
  </div>
<% end %>

app/views/players/show.html.erb
<div class="container px-1">
  <h5><%="#{@player.full_name} Matches"%></h5>
  <%= render partial: 'league_selection' %>
  <%= render partial: 'matches_table' %>
  <%= render 'manage_access_form' %>
</div>