config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  devise_for :users

  root "pages#home"

  resources :players do
    get "league_filter", on: :member
    resources :player_auths, only: [ :create, :destroy ]
  end
  resources :teams
  resources :matches, except: [ :index ]
  # get "filter", on: :collection

  resources :leagues do
    resources :league_auths, only: [ :create, :destroy ]
    get :auths_user_section, to: "league_auths#user_section"
    resources :memberships, only: [ :create, :destroy ]
    get :memberships_player_section, to: "memberships#player_section"
  end

  scope module: :admin do
    resources :users, only: [ :index, :destroy ] do
      post :impersonate, on: :member, to: "impersonations#create"
    end
    delete "/impersonations/stop", to: "impersonations#destroy", as: :stop_impersonating
  end

  if Rails.env.development?
    get "/debug_session", to: "leagues#show_session"
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :league
  has_many :participations, dependent: :destroy
  has_many :players, through: :participations, source: :participant, source_type: "Player"
  accepts_nested_attributes_for :participations
  validates :date, presence: true
  scope :order_by_date, -> { order(date: :desc, created_at: :desc) }

  def number
    if new_record?
      league.matches.size
    else
      earlier_date = league.matches.where("date < ?", self.date).size
      same_day_created_earlier = league.matches.where("date = ?", self.date).where("created_at < ?", self.created_at).size
      earlier_date + same_day_created_earlier + 1
    end
  end

  def top_participations
    max_score = participations.maximum(:score)
    participants = participations.includes(:participant).where(score: max_score).map { |p| p.participant.full_name }
    { winner: participants.join("/"),
      winning_score: max_score }
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_league, only: [ :new ]
  before_action :set_match, only: %i[ show edit update destroy ]
  before_action :set_common_options, only: %i[ new edit create update ]

  # def index
  #   handle_selection
  #   # __method__ returns the current method being called https://apidock.com/ruby/Kernel/__method__
  #   set_options(__method__)
  #   handle_index_response
  # end

  def show
    # @participants = Player.with_league_stats(league_id: @match.league.id).includes(:participations).order("total_score DESC, first_name ASC")
    @participations = @match.participations.includes(:participant).order(score: :desc)
  end

  def new
    set_new_options
    @match = @league.matches.build
    @league.participants_per_match.times { @match.participations.build }
  end

  def edit
    set_edit_options(__method__)
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      flash[:success] = "Match was successfully created."
      redirect_to @match.league
    else
      set_edit_options(__method__)
      # render edit to retain inputs
      render :edit, status: :unprocessable_entity
    end
  end

  def update
    if @match.update(match_params_for_update)
      flash[:success] = "Match was successfully updated."
      redirect_to @match.league
    else
      set_edit_options(__method__)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @match.destroy!
    flash[:success] = "Match was successfully destroyed."
    redirect_to @match.league
  end


  private
    def set_match
      # @match = Match.find(params.expect(:id))
      @match = Match.includes(:participations).find(params[:id])
    end

    def require_league
      # This shouldnt happen, but this approach avoids 'breaking out a of a turbo-stream' if it does
      return unless params[:league_id].blank?

      render turbo_stream: turbo_stream.replace("new_match") {
        helpers.content_tag(:div, class: "p-4 text-center text-danger") do
          flash[:alert] = "Please select a league first."
          helpers.link_to "League somehow got deselected. Please go back to leagues and reselect.", leagues_path, data: { turbo: "false" }, class: "text-danger"
        end
      }
    end

    def set_common_options
      @leagues = current_user.leagues.order_by_created_at
      @league_options = @leagues.map { |league| [ league.full_name, league.id ] }
    end

    def set_new_options
      @league = League.find(params[:league_id].to_i)
      @players = @league.players.order_by_name
      @date = Time.zone.today
    end

    def set_edit_options(method)
      @league = @match.league if method == :create # only relevant when create fails and @match is a new record
      @players = @match.league.players.order_by_name # @match.players would go through the participations association (not what we want)
      @date = @match.date
      @score_hash = @match.participations.index_by(&:participant_id).transform_values(&:score)
      # {23=>10, 24=>5, 25=>0} key is participant id, value is score
    end

    def handle_index_response
      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end

    def match_params
      params.require(:match).permit(
        :date,
        :league_id,
        participations_attributes: [ :score, :participant_id, :participant_type ]
      )
    end

    def match_params_for_update
      params.require(:match).permit(
        :date,
        participations_attributes: [ :id, :score, :participant_id ]
      )
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_dynamic_form.html.erb
<%= form_with(model: match, class: 'admin_form pt-4 my-1',
              data: { controller: "match-form",
                      match_form_players_value: @players.map { |p| { id: p.id, name: p.full_name } }.to_json
                    }) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.date_field :date, value: @date %>
  </div>

  <div class="field">
    <select name="match[league_id]" id="match_league_id" data-action="change->match-form#updateFields">
      <option value="">Select a League</option>
      <% @leagues.each do |league| %>
        <%= tag.option league.full_name, value: league.id, data: { participants_per_match: league.participants_per_match } %>
      <% end %>
    </select>
  </div>

  <div data-match-form-target="participants"></div>

  <%# add submit button dynamically once the user has selected a league %>
  <div data-match-form-target="submit" class="actions mt-3">
    <%#= form.submit %>
  </div>

  <div class='cancel' data-controller="form-cancel"><%= link_to 'X', '#', data: { action: 'form-cancel#cancel' } %> </div>  

<% end %>

app/views/matches/_filter_form.html.erb
<%# redundant %>
<% if false %>
  <div id="matches-filter" class="container px-2 mb-2">
    <div class="container search">
      <hr class = "search mb-1"></hr>

      <%= form_with(url: filter_matches_path, method: "get", class: "form-class", data: {turbo_frame: "matches"}) do %>
        <div class="container mb-1 px-1">
          <div class="row">
            
            <div class="col-4 px-0">
              <fieldset class="">
                <legend class='d-block'>League</legend>          
                <select name="league_id" class= "sort d-block" onchange="this.form.requestSubmit()">
                  <%= options_for_select @league_options, session[:league_id] %>
                </select>
              </fieldset>          
            </div>

          </div>
        </div>
      <% end %>
      <hr class = "search mb-1"></hr>
    </div>
  </div>
<% end %>

app/views/matches/_form.html.erb
<%= form_with(model: match, class: 'admin_form pt-4 my-1') do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>
      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= "#{ @match.new_record? ? 'Add' : 'Edit' } Match #{@match.number}" %>
  </div>

  <% if @match.new_record? %>
    <%= form.hidden_field :league_id, value: @league.id %>
  <% end %>

  <div class="field">
    <%= form.date_field :date, value: @date %>
  </div>

  <%= form.fields_for :participations do |participation_field| %>
   <% index = participation_field.index %>
    <div class="d-flex flex-row mb-0">
      <%= participation_field.select :participant_id,
        options_from_collection_for_select(@players, :id, :full_name, participation_field.object.participant_id.presence || @players[index]&.id) %>
      <%= participation_field.number_field :score, min: -9999, max: 9999, step: 0.1, class: 'ms-1' %>
      <% if @match.new_record? %>
        <%= participation_field.hidden_field :participant_type, value: @league.participant_type.capitalize, class: 'ms-1' %>
      <% end %>
    </div>
  <% end %>

  <div class="actions mt-2">
    <%= form.submit %>
  </div>

  <% if match.new_record? %>
    <div class='cancel' data-controller="form-cancel"><%= link_to 'X', '#', data: { action: 'form-cancel#cancel' } %> </div>  
  <% else %>
    <div class='cancel'><%= link_to 'X', @match.league %> </div>  
  <% end %>  
<% end %>

app/views/matches/_match.html.erb
<%= turbo_frame_tag match do %>
  <div class="row">
    <div class="column"><%= match.date.strftime '%d %b %Y' %></div>
    <div class="column col-2x">
      <%= match.date.strftime '%d %b %Y' %>
    </div>
    <div class="column col-2x"><%= match.top_participations %></div>
    <div class="column"><%= link_to match_path(match) do %>
                                      <i class="bi bi-clipboard"></i>
                                    <% end %>
    </div>
    <div class="column nomobile"><%= link_to edit_match_path(match) do %>
                                               <i class="bi bi-pencil-fill"></i>
                                             <% end %>
    </div>
  </div>
<% end %>

<% if false %>
  <%= turbo_frame_tag match do %>
    <div class="row">
      <div class="column col-2x">
        <%= match.date.strftime('%d/%m/%y') %>
      </div>
      <div class="column col-2x"><%= link_to match.league.name, league_path(match.league, match_id: match.id), class: 'buttonlike', data: {turbo_frame: "show_league_for_match_#{match.id}"} %></div>
      <div class="column col-2x"><%= match.league.season %></div>
      <div class="column"><%= link_to match_path(match) do %>
                                        <i class="bi bi-clipboard"></i>
                                      <% end %>
      </div>
      <div class="column nomobile"><%= link_to edit_match_path(match),
                                              data: {turbo_frame: dom_id(match)} do %>
                                                <i class="bi bi-pencil-fill"></i>
                                              <% end %>
      </div>
    </div>

    <%= turbo_frame_tag "show_league_for_match_#{match.id}" %>
    <%#= require the match in the turbo_frame tag not just the league otherwise matches of the same league will have the same turbo-frame id and league will display in the wrong place %>
    <%#= turbo_frame_tag match.league %>
  <% end %>
<% end %>

app/views/matches/_matches_table.html.erb
<div id="matches-table" class="canvas gray100-canvas embossed mt-1 mb-2">
  <div class="match-league-data container px-0 mb-5">
    <div class="container px-0 mb-5">
      <div class="admin-table mt-2">
        <div class="row fw-bolder">
          <div class="column col-1x">Match</div>
          <div class="column col-2x">Date</div>
          <div class="column col-2x">Winner</div>
          <div class="column col-2x">Winning Score</div>
          <div class="column"></div>
          <div class="column nomobile"></div>
        </div>
      </div>
      <div class="admin-table">
        <% matches_size = @matches.size %>
        <% @matches.each_with_index do |match, index| %>
          <%= turbo_frame_tag match do %>
            <div class="row">
              <div class="column col-1x"><%= matches_size - index %></div>
              <div class="column col-2x"><%= match.date.strftime '%d %b %Y' %></div>
              <div class="column col-2x"><%= match.top_participations[:winner] %></div>
              <div class="column col-2x"><%= match.top_participations[:winning_score] %></div>
              <div class="column"><%= link_to match_path(match) do %>
                                                <i class="bi bi-clipboard"></i>
                                              <% end %>
              </div>
              <div class="column nomobile"><%= link_to edit_match_path(match) do %>
                                                        <i class="bi bi-pencil-fill"></i>
                                                      <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matches/edit.html.erb
<% content_for :title, "Editing match" %>
<%= turbo_frame_tag @match do %>
  <%= render "form", match: @match %>
<% end %>

app/views/matches/index.html.erb
<%# redundant  %>
<if false >
  <%= turbo_frame_tag 'matches' do %>
    <div class="admin-table mt-2">
      <div class="row fw-bolder">
        <div class="column col-1x">Match</div>
        <div class="column col-2x">Date</div>
          <div class="column col-2x">Winner</div>
          <div class="column col-2x">Winning Score</div>
        <div class="column"></div>
        <div class="column nomobile"></div>
      </div>
    </div>
    <div class="admin-table">
      <% matches_size = @matches.size %>    
      <% @matches.each_with_index do |match, index| %>
        <%= turbo_frame_tag match do %>
          <div class="row">
            <div class="column col-1x"><%= matches_size - index %></div>
            <div class="column col-2x"><%= match.date.strftime '%d %b %Y' %></div>
            <div class="column col-2x"><%= match.top_participations[:winner] %></div>
            <div class="column col-2x"><%= match.top_participations[:winning_score] %></div>
            <div class="column"><%= link_to match_path(match) do %>
                                              <i class="bi bi-clipboard"></i>
                                            <% end %>
            </div>
            <div class="column nomobile"><%= link_to edit_match_path(match) do %>
                                                      <i class="bi bi-pencil-fill"></i>
                                                    <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/matches/index.turbo_stream.erb
<%# redundant  %>
<if false >
  <%= turbo_stream.update "matches" do %>
    <%= render partial: "matches_table" %>
  <% end %>
  <%= turbo_stream.update "new_match" do %>
    <%= render inline:'' %>
  <% end %>
  <%= turbo_stream.prepend("flash", partial: "layouts/flash") %>
<% end%>

app/views/matches/new.html.erb
<% content_for :title, "New match" %>
<%= turbo_frame_tag @match do %>
  <div class="col-md-6 mb-4">
    <%#= render "dynamic_form", match: @match %>
    <%= render "form", match: @match %>
  </div>
<% end %>

app/views/matches/show.html.erb
<%= turbo_frame_tag @match do %>
<div id="match-table" class="canvas gray100-canvas embossed mt-1 mb-2">
  <div class="fst-italic ps-2"><%= "Match #{@match.number}, #{@match.date.strftime('%d %b %y')}" %></div>
  <div class="admin-table mt-2 mb-4">
      <div class="row">
        <div class="column col-1x">Name</div>
        <div class="column col-1x">Score</div>
        <div class="column col-1x">Position</div>
      </div>
    <% @participations.each_with_index do |participation, index| %>
      <div class="row">
        <div class="column col-1x"><%= link_to participation.participant.full_name, participation.participant, class: 'buttonlike', data: {turbo: false} %></div>
        <div class="column col-1x"><%= participation.score %></div>
        <div class="column col-1x"><%= index + 1 %></div>
      </div>
    <% end %>
    <div class="cancel">
      <%= link_to image_tag('delete.png', class: "table_icon"), @match.league %>
    </div>
  </div>
<% end %>